### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by shravanbhati** [Infamous-Hydra/YaeMiko#104]
error says My database class name is missing in table... but when I cross checked... class name was were there... don't what's the problem  can you just recheck this repo... or Update with new one it would be helpful

**Comment by Infamous-Hydra** [comment]
Please share the logs at https://t.me/hydraXsupport. We are currently working on releasing a full stable version of this repository soon, where all the bugs will be fixed.

**Comment by Infamous-Hydra** [comment]
> error says My database class name is missing in table... but when I cross checked... class name was were there... don't what's the problem can you just recheck this repo... or Update with new one it would be helpful

Please share the logs at https://t.me/hydraXsupport. We are currently working on releasing a full stable version of this repository soon, where all the bugs will be fixed.

**Comment by hasnainkkk07** [comment]
@Infamous-Hydra Database error

**Comment by hasnainkkk07** [comment]
@hasnainkkk07 Lol

**Comment by shravanbhati** [comment]
I will be waiting for that... I hope You will release soon.
